using PSCommercetools.Provider.Tests.Generator.Extensions;

namespace PSCommercetools.Provider.Tests.Generator;

public sealed class TestDataProviderSourceBuilder
{
    private readonly TestDataProviderMeta provider;

    public TestDataProviderSourceBuilder(TestDataProviderMeta provider)
    {
        this.provider = provider;
    }

    public string Build()
    {
        string lowerEntityNamePlural = provider.EntityNamePlural.FirstCharToLower();
        string lowerEntityName = provider.EntityName.FirstCharToLower();

        return $$"""
                 // <auto-generated/>
                 #nullable enable
                 using System;
                 using System.Collections.Generic;
                 using System.Linq;
                 using Bogus;
                 using commercetools.Sdk.Api.Models.{{provider.CommercetoolsSdkModelNamespaceEntityName}};

                 namespace PSCommercetools.Provider.Tests.TestDataProviders;

                 internal static class {{provider.EntityName}}TestDataProvider
                 {
                     private static int RandomSeed => 37627;

                     public static IEnumerable<{{provider.EntityInterfaceName}}> Get(int count)
                     {
                         return Generate(count);
                     }

                     public static {{provider.EntityInterfaceName}} Get()
                     {
                         return Generate(1).First();
                     }

                     public static {{provider.CommercetoolsSdkPagedQueryResponseName}} AsPagedQueryResponse(
                         this IEnumerable<{{provider.EntityInterfaceName}}> {{lowerEntityNamePlural}},
                         long limit = 20,
                         long offset = 0,
                         bool withTotal = true)
                     {
                         List<{{provider.EntityInterfaceName}}> {{lowerEntityName}}List = {{lowerEntityNamePlural}}.ToList();

                         var count = (int)CalculateCount({{lowerEntityName}}List.Count, limit, offset);

                         return new {{provider.CommercetoolsSdkPagedQueryResponseName}}
                         {
                             Limit = limit,
                             Offset = offset,
                             Count = count,
                             Total = withTotal ? {{lowerEntityName}}List.Count : null,
                             Results = {{lowerEntityName}}List.Skip((int)offset).Take(count).ToList()
                         };
                     }

                     private static long CalculateCount(int numberOfItems, long limit, long offset)
                     {
                         if (offset >= numberOfItems)
                         {
                             return 0;
                         }

                         long remainingItems = numberOfItems - offset;
                         return Math.Min(limit, remainingItems);
                     }

                     private static List<{{provider.EntityInterfaceName}}> Generate(int count)
                     {
                         Randomizer.Seed = new Random(RandomSeed);

                         Faker<commercetools.Sdk.Api.Models.{{provider.CommercetoolsSdkModelNamespaceEntityName}}.{{provider.EntityName}}> {{lowerEntityName}}Faker = new Faker<commercetools.Sdk.Api.Models.{{provider.CommercetoolsSdkModelNamespaceEntityName}}.{{provider.EntityName}}>()
                             .RuleFor(o => o.Id, faker => faker.Random.Guid().ToString())
                             {{(provider.HasKey ? ".RuleFor(o => o.Key, faker => faker.Random.Guid().ToString())" : string.Empty)}}
                             {{(provider.HasVersion ? ".RuleFor(o => o.Version, faker => faker.Random.Int(1, 10))" : string.Empty)}}
                             {{(provider.HasContainer ? ".RuleFor(o => o.Container, faker => \"container\")" : string.Empty)}}
                             {{(provider.HasLastModifiedAt ? ".RuleFor(o => o.LastModifiedAt, faker => faker.Date.Recent(30))" : string.Empty)}}
                             .RuleFor(o => o.CreatedAt, faker => faker.Date.Recent(30));
                             
                         return {{lowerEntityName}}Faker.Generate(count).Cast<{{provider.EntityInterfaceName}}>().ToList();
                     }
                 }
                 """;
    }
}