using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PSCommercetools.Provider.Generator;

[Generator]
public class EntitiesGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<EntityMetadata> entityMetadataValues =
            context.SyntaxProvider
                .CreateSyntaxProvider(
                    (node, _) => node is ClassDeclarationSyntax,
                    (transformContext, _) => (ClassDeclarationSyntax)transformContext.Node)
                .Where(c => c.AttributeLists
                    .SelectMany(al => al.Attributes)
                    .Any(a => a.Name.ToString().Contains("GenerateEntity")))
                .Select((declaration, _) => EntityMetadata.CreateFrom(declaration));

        IncrementalValueProvider<(Compilation Left,
            ImmutableArray<EntityMetadata> Right)> incrementalValueProvider =
            context.CompilationProvider.Combine(entityMetadataValues.Collect());

        context.RegisterSourceOutput(incrementalValueProvider,
            (productionContext, source) => { productionContext.AddSource("Entities.g.cs", BuildSource(source.Right.ToList())); });
    }

    private static string BuildSource(List<EntityMetadata> source)
    {
        var stringBuilder = new StringBuilder($$"""
                                                // <auto-generated/>
                                                #nullable enable
                                                using System;
                                                using System.Collections.Generic;
                                                using PSCommercetools.Provider.SdkProxyLayer;
                                                using PSCommercetools.Provider.SdkProxyLayer.Generated;
                                                using PSCommercetools.Provider.EntityServiceLayer;
                                                using PSCommercetools.Provider.EntityServiceLayer.Services;
                                                using PSCommercetools.Provider.EntityServiceLayer.Generated;
                                                using PSCommercetools.Provider.RepositoryLayer;

                                                namespace PSCommercetools.Provider.EntityServiceLayer.Generated
                                                {
                                                  public static partial class Entities
                                                  {
                                                      public static List<string> EntitiesList {get;} = new List<string>()
                                                      {
                                                {{BuildEntitiesList(source)}}
                                                      };
                                                      
                                                      internal static List<IEntityContainerService> BuildEntityServicesList(CommercetoolsEntityRepository commercetoolsEntityRepository) => new List<IEntityContainerService>()
                                                      {
                                                {{BuildEntityContainerServicesList(source)}}
                                                      };
                                                      
                                                      internal static IBaseEntityService? GetCommercetoolsContainerEntityService(CommercetoolsEntityRepository commercetoolsEntityRepository, string entityName)
                                                      {
                                                        return entityName switch
                                                        {
                                                {{BuildCommercetoolsEntityContainerServicesList(source)}}
                                                                _ => null
                                                        };
                                                      }
                                                  }
                                                }
                                                """);

        return stringBuilder.ToString();
    }

    private static string BuildEntitiesList(List<EntityMetadata> source)
    {
        var stringBuilder = new StringBuilder();

        source.ForEach((s, last) =>
        {
            stringBuilder.AppendLineConditional(!last, $"""
                                                                    "{s.EntityNamePlural.ToLowerInvariant()}",
                                                        """);
        });

        return stringBuilder.ToString();
    }

    private static string BuildEntityContainerServicesList(List<EntityMetadata> source)
    {
        var stringBuilder = new StringBuilder();

        source.ForEach((s, last) =>
        {
            if (s.SkipEntityService)
            {
                return;
            }

            var fullInterfaceName =
                $"commercetools.Sdk.Api.Models.{s.CommercetoolsSdkModelNamespaceEntityName}.{s.EntityInterfaceName}";

            stringBuilder.AppendLineConditional(!last,
                $"""            new CommercetoolsContainerEntityService<{fullInterfaceName}>(commercetoolsEntityRepository, "{s.EntityNamePlural.ToLowerInvariant()}"),""");
        });

        return stringBuilder.ToString();
    }

    private static string BuildCommercetoolsEntityContainerServicesList(List<EntityMetadata> source)
    {
        var stringBuilder = new StringBuilder();

        source.ForEach((s, last) =>
        {
            if (s.SkipEntityService)
            {
                return;
            }

            var fullInterfaceName =
                $"commercetools.Sdk.Api.Models.{s.CommercetoolsSdkModelNamespaceEntityName}.{s.EntityInterfaceName}";

            stringBuilder.AppendLineConditional(!last,
                $"""            var name and "{s.EntityNamePlural.ToLowerInvariant()}" => new CommercetoolsContainerEntityService<{fullInterfaceName}>(commercetoolsEntityRepository, name),""");
        });

        return stringBuilder.ToString();
    }
}