using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace PSCommercetools.Provider.Generator;

[Generator]
public class SdkProxyDictionaryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<SdkProxyMetadata> entityMetadataValues =
            context.SyntaxProvider
                .CreateSyntaxProvider(
                    (node, _) => node is ClassDeclarationSyntax,
                    (transformContext, _) => (ClassDeclarationSyntax)transformContext.Node)
                .Where(c => c.AttributeLists
                    .SelectMany(al => al.Attributes)
                    .Any(a => a.Name.ToString().Contains("GenerateSdkProxy")))
                .Select((declaration, _) => SdkProxyMetadata.CreateFrom(declaration));

        IncrementalValueProvider<(Compilation Left,
            ImmutableArray<SdkProxyMetadata> Right)> incrementalValueProvider =
            context.CompilationProvider.Combine(entityMetadataValues.Collect());

        context.RegisterSourceOutput(incrementalValueProvider,
            (productionContext, source) => { productionContext.AddSource("Entities.g.cs", BuildSource(source.Right.ToList())); });
    }

    private static string BuildSource(List<SdkProxyMetadata> source)
    {
        var stringBuilder = new StringBuilder($$"""
                                                // <auto-generated/>
                                                using System;
                                                using System.Collections.Generic;
                                                using PSCommercetools.Provider.SdkProxyLayer;
                                                using PSCommercetools.Provider.SdkProxyLayer.Generated;

                                                namespace PSCommercetools.Provider.EntityServiceLayer.Generated
                                                {
                                                  public static partial class Entities
                                                  {
                                                      public static Dictionary<Type, ISdkProxy> SdkProxiesDictionary { get; } = new()
                                                      {
                                                {{BuildSdkProxiesDictionaryItems(source)}}
                                                      };
                                                  }
                                                }
                                                """);

        return stringBuilder.ToString();
    }

    private static string BuildSdkProxiesDictionaryItems(List<SdkProxyMetadata> source)
    {
        var stringBuilder = new StringBuilder();

        source.ForEach((s, last) =>
        {
            var typeName =
                $"commercetools.Sdk.Api.Models.{s.CommercetoolsSdkModelNamespaceEntityName}.{s.EntityInterfaceName}";

            stringBuilder.AppendLineConditional(!last, $$"""
                                                                  { typeof({{typeName}}), new {{s.EntityName}}SdkProxy() },
                                                         """);
        });

        return stringBuilder.ToString();
    }
}

internal static class StringBuilderExtensions
{
    public static void AppendLineConditional(this StringBuilder stringBuilder, bool newLine, string value)
    {
        if (newLine)
        {
            stringBuilder.AppendLine(value);
            return;
        }

        stringBuilder.Append(value);
    }
}

internal static class ListExtensions
{
    public static void ForEach<T>(this List<T> list, Action<T, bool> action)
    {
        for (var i = 0; i < list.Count; i++)
        {
            action(list[i], i == list.Count - 1);
        }
    }
}