namespace PSCommercetools.Provider.Generator;

internal sealed class SdkProxySourceBuilder(SdkProxyMetadata sdkProxyMetadata)
{
    public string Build()
    {
        return $$"""
                 // <auto-generated/>
                 #nullable enable
                 using System;
                 using System.Linq;
                 using System.Net;
                 using System.Collections.Generic;
                 using commercetools.Sdk.Api.Client;
                 using commercetools.Sdk.Api.Models.{{sdkProxyMetadata.CommercetoolsSdkModelNamespaceEntityName}};
                 using commercetools.Sdk.Api.Client.RequestBuilders.{{sdkProxyMetadata.EntityNamePlural}};
                 using commercetools.Sdk.Api.Serialization;
                 using PSCommercetools.Provider.EntityServiceLayer;
                 using PSCommercetools.Provider.SdkProxyLayer;
                 using PSCommercetools.Provider.SdkProxyLayer.Extensions;
                 using System.Management.Automation;

                 namespace PSCommercetools.Provider.SdkProxyLayer.Generated
                 {
                     internal partial class {{sdkProxyMetadata.EntityName}}SdkProxy : SdkProxyBase, ISdkProxy<{{sdkProxyMetadata.EntityInterfaceName}}>
                     {
                         public Type EntityType => typeof({{sdkProxyMetadata.EntityInterfaceName}});

                         {{CreateGetFuncBody()}}
                         
                         {{CreateExistsByIdFuncBody()}}
                         
                         {{CreateGetByIdFuncBody()}}
                         
                         {{CreateDeleteFuncBody()}}
                         
                         {{CreateCreateFuncBody()}}
                         
                         {{CreateUpdateFuncBody()}}
                     }
                 }
                 """;
    }

    private string CreateGetFuncBody()
    {
        return $$"""
                  public Func<ProjectApiRoot, string[]?, string?, long?, long?, string?, bool?, EntitiesContainer<{{sdkProxyMetadata.EntityInterfaceName}}>> GetFunc =>(p, expands, where, limit, offset, sort, withCount) =>
                  {
                      ByProjectKey{{sdkProxyMetadata.EntityNamePlural}}Get? byProjectKeyGet = p.{{sdkProxyMetadata.EntityNamePlural}}().Get();
                      
                      AddExpandClauses(byProjectKeyGet, expands);
                      AddWhereClause(byProjectKeyGet, where);
                      AddLimitClause(byProjectKeyGet, limit);
                      AddOffsetClause(byProjectKeyGet, offset);
                      AddSortClause(byProjectKeyGet, sort);
                      AddWithTotalClause(byProjectKeyGet, withCount);

                      {{sdkProxyMetadata.CommercetoolsSdkPagedQueryResponseName}}? response = byProjectKeyGet.ExecuteAsync().GetAwaiter().GetResult();

                      return response.Results.ToEntitiesContainer<{{sdkProxyMetadata.EntityInterfaceName}}>(response.Count, response.Offset, response.Limit, response.Total);
                  };
                 """;
    }

    private string CreateExistsByIdFuncBody()
    {
        return $"""
                public Func<ProjectApiRoot, string, bool> ExistsByIdFunc => (p, id) => 
                p.{sdkProxyMetadata.EntityNamePlural}().WithId(id).Head().SendAsync().GetAwaiter().GetResult().StatusCode != HttpStatusCode.NotFound;
                """;
    }

    private string CreateGetByIdFuncBody()
    {
        return $$"""
                 public virtual Func<ProjectApiRoot, string, string[]?, {{sdkProxyMetadata.EntityInterfaceName}}> GetByIdFunc =>
                 (p, id, expands) => 
                 {
                     var getMethod = p
                         .{{sdkProxyMetadata.EntityNamePlural}}()
                         .WithId(id)
                         .Get();

                     getMethod = (expands ?? []).Aggregate(getMethod, (current, expand) => current.WithExpand(expand));

                     return getMethod.ExecuteAsync()
                         .GetAwaiter()
                         .GetResult();
                 };
                 """;
    }

    private string CreateDeleteFuncBody()
    {
        return $$"""
                 public Func<ProjectApiRoot, {{sdkProxyMetadata.EntityInterfaceName}}, string[]?, {{sdkProxyMetadata.EntityInterfaceName}}> DeleteFunc =>
                 (p, e, expands) =>
                 {
                 var deleteMethod = p.{{sdkProxyMetadata.EntityNamePlural}}().WithId(e.Id).Delete().WithVersion(e.Version);
                 deleteMethod = (expands ?? []).Aggregate(deleteMethod, (current, expand) => current.WithExpand(expand));
                 return deleteMethod.ExecuteAsync().GetAwaiter().GetResult();
                 };
                 """;
    }

    private string CreateCreateFuncBody()
    {
        var func =
            $"public Func<ProjectApiRoot, SerializerService, string, string[]?, {sdkProxyMetadata.EntityInterfaceName}> CreateFunc => (p, s, j, expands) =>";

        return sdkProxyMetadata.SupportsCreate
            ? $$"""
                {{func}}
                {
                    var draft = s.Deserialize<{{sdkProxyMetadata.EntityInterfaceName}}Draft>(j);
                    
                    var createMethod = p.{{sdkProxyMetadata.EntityNamePlural}}().Post(draft);
                    createMethod = (expands ?? []).Aggregate(createMethod, (current, expand) => current.WithExpand(expand));
                    return createMethod.ExecuteAsync().GetAwaiter().GetResult(){{sdkProxyMetadata.SubtypeToReturnFromCreate}};
                };
                """
            : $"{func} throw new NotImplementedException();";
    }

    private string CreateUpdateFuncBody()
    {
        return $$"""
                 public Func<ProjectApiRoot, SerializerService, {{sdkProxyMetadata.EntityInterfaceName}}, object, string[]?, {{sdkProxyMetadata.EntityInterfaceName}}> UpdateFunc => (p, s, e, aj, expands) =>
                 {
                     List<{{sdkProxyMetadata.EntityInterfaceName}}UpdateAction>? actions = aj switch
                     {
                         string actionsString => s.Deserialize<List<{{sdkProxyMetadata.EntityInterfaceName}}UpdateAction>>(actionsString),
                         PSObject psObject => psObject.BaseObject as List<{{sdkProxyMetadata.EntityInterfaceName}}UpdateAction>,
                         List<{{sdkProxyMetadata.EntityInterfaceName}}UpdateAction> list => list, 
                         _ => null
                     };

                     ArgumentNullException.ThrowIfNull(actions);

                     var update = new {{sdkProxyMetadata.EntityName}}Update
                     {
                         Version = e.Version,
                         Actions = actions
                     };

                     var updateMethod = p.{{sdkProxyMetadata.EntityNamePlural}}().WithId(e.Id).Post(update);
                     updateMethod = (expands ?? []).Aggregate(updateMethod, (current, expand) => current.WithExpand(expand));
                     return updateMethod.ExecuteAsync().GetAwaiter().GetResult();
                 };
                 """;
    }
}